import { HoverEntry, escOp, escMd, op } from '../../types';

export const hoverData: Record<string, HoverEntry> = {
  // ── Data movement ────────────────────────────────────────────────────────────
  'vmov':     (ops) => `**vmov** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Move between ARM core registers and VFP single-precision registers`,
  'vmovs':    (ops) => `**vmovs** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Copy VFP single-precision register`,
  'vmovd':    (ops) => `**vmovd** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Copy VFP double-precision register`,

  // ── VFP Loads / Stores ───────────────────────────────────────────────────────
  'vldr':     (ops) => `**vldr** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Load VFP single-precision register from memory`,
  'vldm':     (ops) => `**vldm** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Load multiple VFP registers`,
  'vstr':     (ops) => `**vstr** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Store VFP single-precision register to memory`,
  'vstm':     (ops) => `**vstm** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Store multiple VFP registers`,
  'vpush':    (ops) => `**vpush** \`${escOp(ops,0)}\` — Push VFP registers ${escMd(op(ops,0))} onto stack`,
  'vpop':     (ops) => `**vpop** \`${escOp(ops,0)}\` — Pop VFP registers from stack into ${escMd(op(ops,0))}`,

  // ── VFP / FPU ────────────────────────────────────────────────────────────────
  'vadd':     (ops) => `**vadd** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — VFP add: \`${escOp(ops,0)} = ${escOp(ops,1)} + ${escOp(ops,2)}\``,
  'vsub':     (ops) => `**vsub** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — VFP subtract: \`${escOp(ops,0)} = ${escOp(ops,1)} - ${escOp(ops,2)}\``,
  'vmul':     (ops) => `**vmul** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — VFP multiply: \`${escOp(ops,0)} = ${escOp(ops,1)} × ${escOp(ops,2)}\``,
  'vdiv':     (ops) => `**vdiv** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — VFP divide: \`${escOp(ops,0)} = ${escOp(ops,1)} / ${escOp(ops,2)}\``,
  'vnmul':    (ops) => `**vnmul** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — VFP negate multiply: \`${escOp(ops,0)} = -(${escOp(ops,1)} × ${escOp(ops,2)})\``,
  'vmla':     (ops) => `**vmla** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — VFP multiply-accumulate: \`${escOp(ops,0)} = ${escOp(ops,0)} + (${escOp(ops,1)} × ${escOp(ops,2)})\``,
  'vmls':     (ops) => `**vmls** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — VFP multiply-subtract: \`${escOp(ops,0)} = ${escOp(ops,0)} - (${escOp(ops,1)} × ${escOp(ops,2)})\``,
  'vnmla':    (ops) => `**vnmla** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — VFP negate multiply-accumulate: \`${escOp(ops,0)} = -(${escOp(ops,0)} + (${escOp(ops,1)} × ${escOp(ops,2)}))\``,
  'vnmls':    (ops) => `**vnmls** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — VFP negate multiply-subtract: \`${escOp(ops,0)} = -(${escOp(ops,0)} - (${escOp(ops,1)} × ${escOp(ops,2)}))\``,
  'vcmp':     (ops) => `**vcmp** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — VFP compare ${escMd(op(ops,0))} vs ${escMd(op(ops,1))}, result written to FPSCR`,
  'vcmpe':    (ops) => `**vcmpe** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — VFP compare with invalid operation on NaN`,
  'vcvt':     (ops) => `**vcvt** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — VFP convert between integer and floating-point`,
  'vcvtr':    (ops) => `**vcvtr** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — VFP convert with rounding`,
  'vsqrt':    (ops) => `**vsqrt** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — VFP square root: \`${escOp(ops,0)} = sqrt(${escOp(ops,1)})\``,
  'vabs':     (ops) => `**vabs** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — VFP absolute value: \`${escOp(ops,0)} = |${escOp(ops,1)}|\``,
  'vneg':     (ops) => `**vneg** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — VFP negate: \`${escOp(ops,0)} = -${escOp(ops,1)}\``,
  'vmrs':     (ops) => `**vmrs** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Move VFP system register ${escMd(op(ops,1))} to ARM core register ${escMd(op(ops,0))}`,
  'vmsr':     (ops) => `**vmsr** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Move ARM core register ${escMd(op(ops,1))} to VFP system register ${escMd(op(ops,0))}`,
  'fmrx':     (ops) => `**fmrx** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Move VFP system register to ARM core register (legacy alias for vmrs)`,
  'fmxr':     (ops) => `**fmxr** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Move ARM core register to VFP system register (legacy alias for vmsr)`,
  'fmstat':   '**fmstat** — Transfer FPSCR flags to APSR (alias for vmrs APSR_nzcv, FPSCR)',

  // ── DSP SIMD ─────────────────────────────────────────────────────────────────
  'sadd8':    '**sadd8** — Signed byte addition in 4 lanes',
  'sadd16':   '**sadd16** — Signed halfword addition in 2 lanes',
  'shadd8':   '**shadd8** — Signed halving byte addition (result >> 1) in 4 lanes',
  'shadd16':  '**shadd16** — Signed halving halfword addition in 2 lanes',
  'ssub8':    '**ssub8** — Signed byte subtraction in 4 lanes',
  'ssub16':   '**ssub16** — Signed halfword subtraction in 2 lanes',
  'shsub8':   '**shsub8** — Signed halving byte subtraction in 4 lanes',
  'shsub16':  '**shsub16** — Signed halving halfword subtraction in 2 lanes',
  'uadd8':    '**uadd8** — Unsigned byte addition in 4 lanes',
  'uadd16':   '**uadd16** — Unsigned halfword addition in 2 lanes',
  'uhadd8':   '**uhadd8** — Unsigned halving byte addition in 4 lanes',
  'uhadd16':  '**uhadd16** — Unsigned halving halfword addition in 2 lanes',
  'usub8':    '**usub8** — Unsigned byte subtraction in 4 lanes',
  'usub16':   '**usub16** — Unsigned halfword subtraction in 2 lanes',
  'uhsub8':   '**uhsub8** — Unsigned halving byte subtraction in 4 lanes',
  'uhsub16':  '**uhsub16** — Unsigned halving halfword subtraction in 2 lanes',
  'qadd':     '**qadd** — Saturating add',
  'qsub':     '**qsub** — Saturating subtract',
  'qdadd':    '**qdadd** — Saturating doubling add',
  'qdsub':    '**qdsub** — Saturating doubling subtract',
  'smuad':    '**smuad** — Signed dual multiply add',
  'smusd':    '**smusd** — Signed dual multiply subtract',
  'smlad':    '**smlad** — Signed multiply add dual',
  'smlsd':    '**smlsd** — Signed multiply subtract dual',
  'smlald':   '**smlald** — Signed multiply accumulate long dual',
  'smlsld':   '**smlsld** — Signed multiply subtract long dual',
  'smmla':    '**smmla** — Signed most significant word multiply accumulate',
  'smmls':    '**smmls** — Signed most significant word multiply subtract',
  'smmul':    '**smmul** — Signed most significant word multiply',
  'usad8':    '**usad8** — Unsigned sum of absolute differences (4 bytes)',
  'usada8':   '**usada8** — Unsigned sum of absolute differences accumulated',
};
