/**
 * Hover descriptions for Cortex-M33 / Thumb-2 mnemonics.
 * Keys are lowercase mnemonic strings. Add entries freely.
 */
export const hoverData: Record<string, string> = {
  // ── Stack ────────────────────────────────────────────────────────────────────
  'push':     '**push** `{reglist}` — Push registers onto the full-descending stack (pre-decrement SP)',
  'pop':      '**pop** `{reglist}` — Pop registers from stack; if PC in list, branches to popped value (function return)',

  // ── Data movement ────────────────────────────────────────────────────────────
  'mov':      '**mov** `Rd, Op2` — Move: `Rd = Op2` (does not update flags)',
  'movs':     '**movs** `Rd, Op2` — Move and update N/Z flags',
  'movw':     '**movw** `Rd, #imm16` — Move 16-bit immediate into lower half of Rd (zero-extends)',
  'movt':     '**movt** `Rd, #imm16` — Move 16-bit immediate into upper half of Rd (lower half unchanged)',
  'msr':      '**msr** `spec_reg, Rn` — Move core register to special register (e.g. MSP, PSP, CONTROL)',
  'mrs':      '**mrs** `Rd, spec_reg` — Move special register to core register',
  'vmov':     '**vmov** `Sd, Rn` / `Rd, Sn` — Move between ARM core registers and VFP single-precision registers',
  'vmovs':    '**vmovs** `Sd, Sm` — Copy VFP single-precision register',
  'vmovd':    '**vmovd** `Dd, Dm` — Copy VFP double-precision register',

  // ── Loads ────────────────────────────────────────────────────────────────────
  'ldr':      '**ldr** `Rt, [Rn, #off]` — Load 32-bit word from memory',
  'ldrb':     '**ldrb** `Rt, [Rn, #off]` — Load byte (zero-extended to 32 bits)',
  'ldrh':     '**ldrh** `Rt, [Rn, #off]` — Load halfword (zero-extended)',
  'ldrsb':    '**ldrsb** `Rt, [Rn, #off]` — Load byte (sign-extended)',
  'ldrsh':    '**ldrsh** `Rt, [Rn, #off]` — Load halfword (sign-extended)',
  'ldr.w':    '**ldr.w** `Rt, [Rn, #off]` — 32-bit Thumb-2 encoding of ldr (wider immediate range)',
  'ldrb.w':   '**ldrb.w** `Rt, [Rn, #off]` — 32-bit Thumb-2 encoding of ldrb',
  'ldrh.w':   '**ldrh.w** `Rt, [Rn, #off]` — 32-bit Thumb-2 encoding of ldrh',
  'ldm':      '**ldm** `Rn, {reglist}` — Load multiple registers from consecutive addresses',
  'ldmia':    '**ldmia** `Rn!, {reglist}` — Load multiple, increment after (Rn updated)',
  'vldr':     '**vldr** `Sd, [Rn, #off]` — Load VFP single-precision register from memory',
  'vldm':     '**vldm** `Rn, {slist}` — Load multiple VFP registers',

  // ── Stores ───────────────────────────────────────────────────────────────────
  'str':      '**str** `Rt, [Rn, #off]` — Store 32-bit word to memory',
  'strb':     '**strb** `Rt, [Rn, #off]` — Store byte to memory',
  'strh':     '**strh** `Rt, [Rn, #off]` — Store halfword to memory',
  'str.w':    '**str.w** `Rt, [Rn, #off]` — 32-bit Thumb-2 encoding of str',
  'strb.w':   '**strb.w** `Rt, [Rn, #off]` — 32-bit Thumb-2 encoding of strb',
  'strh.w':   '**strh.w** `Rt, [Rn, #off]` — 32-bit Thumb-2 encoding of strh',
  'stm':      '**stm** `Rn, {reglist}` — Store multiple registers',
  'stmia':    '**stmia** `Rn!, {reglist}` — Store multiple, increment after',
  'stmdb':    '**stmdb** `Rn!, {reglist}` — Store multiple, decrement before',
  'vstr':     '**vstr** `Sd, [Rn, #off]` — Store VFP single-precision register to memory',
  'vstm':     '**vstm** `Rn, {slist}` — Store multiple VFP registers',
  'vpush':    '**vpush** `{slist}` — Push VFP registers onto stack',
  'vpop':     '**vpop** `{slist}` — Pop VFP registers from stack',

  // ── Arithmetic ───────────────────────────────────────────────────────────────
  'add':      '**add** `Rd, Rn, Op2` — Add',
  'adds':     '**adds** `Rd, Rn, Op2` — Add and update N/Z/C/V flags',
  'add.w':    '**add.w** `Rd, Rn, Op2` — 32-bit Thumb-2 add',
  'sub':      '**sub** `Rd, Rn, Op2` — Subtract',
  'subs':     '**subs** `Rd, Rn, Op2` — Subtract and update flags',
  'sub.w':    '**sub.w** `Rd, Rn, Op2` — 32-bit Thumb-2 subtract',
  'rsb':      '**rsb** `Rd, Rn, Op2` — Reverse subtract: `Rd = Op2 - Rn`',
  'rsbs':     '**rsbs** `Rd, Rn, Op2` — Reverse subtract and update flags',
  'adc':      '**adc** `Rd, Rn, Op2` — Add with carry: `Rd = Rn + Op2 + C`',
  'adcs':     '**adcs** `Rd, Rn, Op2` — Add with carry, update flags',
  'sbc':      '**sbc** `Rd, Rn, Op2` — Subtract with carry: `Rd = Rn - Op2 - ~C`',
  'sbcs':     '**sbcs** `Rd, Rn, Op2` — Subtract with carry, update flags',
  'mul':      '**mul** `Rd, Rn, Rm` — Multiply (lower 32 bits)',
  'mla':      '**mla** `Rd, Rn, Rm, Ra` — Multiply-accumulate: `Rd = Ra + Rn×Rm`',
  'mls':      '**mls** `Rd, Rn, Rm, Ra` — Multiply-subtract: `Rd = Ra - Rn×Rm`',
  'umull':    '**umull** `RdLo, RdHi, Rn, Rm` — Unsigned multiply long (64-bit result)',
  'smull':    '**smull** `RdLo, RdHi, Rn, Rm` — Signed multiply long (64-bit result)',
  'sdiv':     '**sdiv** `Rd, Rn, Rm` — Signed integer divide: `Rd = Rn / Rm`',
  'udiv':     '**udiv** `Rd, Rn, Rm` — Unsigned integer divide: `Rd = Rn / Rm`',

  // ── Logical / Shift ──────────────────────────────────────────────────────────
  'and':      '**and** `Rd, Rn, Op2` — Bitwise AND',
  'ands':     '**ands** `Rd, Rn, Op2` — Bitwise AND, update flags',
  'orr':      '**orr** `Rd, Rn, Op2` — Bitwise OR',
  'orrs':     '**orrs** `Rd, Rn, Op2` — Bitwise OR, update flags',
  'eor':      '**eor** `Rd, Rn, Op2` — Bitwise exclusive OR',
  'eors':     '**eors** `Rd, Rn, Op2` — Bitwise XOR, update flags',
  'bic':      '**bic** `Rd, Rn, Op2` — Bit clear: `Rd = Rn & ~Op2`',
  'bics':     '**bics** `Rd, Rn, Op2` — Bit clear, update flags',
  'mvn':      '**mvn** `Rd, Op2` — Bitwise NOT: `Rd = ~Op2`',
  'mvns':     '**mvns** `Rd, Op2` — Bitwise NOT, update flags',
  'lsl':      '**lsl** `Rd, Rn, Rs/#imm` — Logical shift left',
  'lsls':     '**lsls** `Rd, Rn, Rs/#imm` — Logical shift left, update flags',
  'lsr':      '**lsr** `Rd, Rn, Rs/#imm` — Logical shift right',
  'lsrs':     '**lsrs** `Rd, Rn, Rs/#imm` — Logical shift right, update flags',
  'asr':      '**asr** `Rd, Rn, Rs/#imm` — Arithmetic shift right (sign-extending)',
  'asrs':     '**asrs** `Rd, Rn, Rs/#imm` — Arithmetic shift right, update flags',
  'ror':      '**ror** `Rd, Rn, Rs/#imm` — Rotate right',
  'rors':     '**rors** `Rd, Rn, Rs/#imm` — Rotate right, update flags',
  'rrx':      '**rrx** `Rd, Rn` — Rotate right extended through carry',
  'clz':      '**clz** `Rd, Rn` — Count leading zeros',
  'rev':      '**rev** `Rd, Rn` — Reverse byte order in 32-bit word',
  'rev16':    '**rev16** `Rd, Rn` — Reverse bytes in each halfword',
  'revsh':    '**revsh** `Rd, Rn` — Reverse bytes in lower halfword and sign-extend',
  'sxth':     '**sxth** `Rd, Rn` — Sign-extend halfword to 32 bits',
  'sxtb':     '**sxtb** `Rd, Rn` — Sign-extend byte to 32 bits',
  'uxth':     '**uxth** `Rd, Rn` — Zero-extend halfword to 32 bits',
  'uxtb':     '**uxtb** `Rd, Rn` — Zero-extend byte to 32 bits',
  'uxtab':    '**uxtab** `Rd, Rn, Rm` — Zero-extend byte and add',
  'sxtab':    '**sxtab** `Rd, Rn, Rm` — Sign-extend byte and add',
  'pld':      '**pld** `[Rn, #off]` — Preload data hint (prefetch cache line)',

  // ── Compare / Test ───────────────────────────────────────────────────────────
  'cmp':      '**cmp** `Rn, Op2` — Compare: sets N/Z/C/V flags from `Rn - Op2`, discards result',
  'cmn':      '**cmn** `Rn, Op2` — Compare negative: flags from `Rn + Op2`',
  'tst':      '**tst** `Rn, Op2` — Test bits: N/Z flags from `Rn & Op2`',
  'teq':      '**teq** `Rn, Op2` — Test equivalence: N/Z flags from `Rn ^ Op2`',

  // ── Branches ─────────────────────────────────────────────────────────────────
  'b':        '**b** `label` — Unconditional branch',
  'b.n':      '**b.n** `label` — Narrow (16-bit) unconditional branch',
  'b.w':      '**b.w** `label` — Wide (32-bit) unconditional branch (larger range)',
  'bl':       '**bl** `label` — Branch with link: `lr = next instruction; jump to label` (call)',
  'blx':      '**blx** `Rm` — Branch with link and exchange (can switch ARM/Thumb state)',
  'bx':       '**bx** `Rm` — Branch and exchange: jump to Rm, bit[0] selects Thumb/ARM',
  'beq':      '**beq** `label` — Branch if Z == 1 (equal)',
  'bne':      '**bne** `label` — Branch if Z == 0 (not equal)',
  'bcs':      '**bcs** `label` — Branch if C == 1 (carry set / unsigned higher or same)',
  'bcc':      '**bcc** `label` — Branch if C == 0 (carry clear / unsigned lower)',
  'bmi':      '**bmi** `label` — Branch if N == 1 (minus / negative)',
  'bpl':      '**bpl** `label` — Branch if N == 0 (plus / non-negative)',
  'bvs':      '**bvs** `label` — Branch if V == 1 (overflow set)',
  'bvc':      '**bvc** `label` — Branch if V == 0 (overflow clear)',
  'bge':      '**bge** `label` — Branch if N == V (signed greater or equal)',
  'blt':      '**blt** `label` — Branch if N ≠ V (signed less than)',
  'bgt':      '**bgt** `label` — Branch if Z == 0 and N == V (signed greater than)',
  'ble':      '**ble** `label` — Branch if Z == 1 or N ≠ V (signed less or equal)',
  'bhi':      '**bhi** `label` — Branch if C == 1 and Z == 0 (unsigned higher)',
  'bls':      '**bls** `label` — Branch if C == 0 or Z == 1 (unsigned lower or same)',
  'cbz':      '**cbz** `Rn, label` — Compare and branch if zero (no flag update, short range)',
  'cbnz':     '**cbnz** `Rn, label` — Compare and branch if non-zero',
  'it':       '**it** `cond` — If-Then block: next instruction is conditional on cond',
  'ite':      '**ite** `cond` — If-Then-Else block: 2 conditional instructions',
  'itt':      '**itt** `cond` — If-Then-Then: 2 instructions with same condition',
  'itee':     '**itee** `cond` — If-Then-Else-Else: 3 conditional instructions',

  // ── VFP / FPU ────────────────────────────────────────────────────────────────
  'vadd':     '**vadd** `Sd, Sn, Sm` — VFP floating-point add',
  'vsub':     '**vsub** `Sd, Sn, Sm` — VFP floating-point subtract',
  'vmul':     '**vmul** `Sd, Sn, Sm` — VFP floating-point multiply',
  'vdiv':     '**vdiv** `Sd, Sn, Sm` — VFP floating-point divide',
  'vcmp':     '**vcmp** `Sd, Sm` — VFP compare, result written to FPSCR',
  'vcmpe':    '**vcmpe** `Sd, Sm` — VFP compare with invalid operation on NaN',
  'vcvt':     '**vcvt** `Sd, Sm` — VFP convert between integer and floating-point',
  'vcvtr':    '**vcvtr** `Sd, Sm` — VFP convert with rounding',
  'vsqrt':    '**vsqrt** `Sd, Sm` — VFP square root',
  'vabs':     '**vabs** `Sd, Sm` — VFP absolute value',
  'vneg':     '**vneg** `Sd, Sm` — VFP negate',
  'vmrs':     '**vmrs** `Rd, FPSCR` — Move VFP system register to ARM core register',
  'vmsr':     '**vmsr** `FPSCR, Rn` — Move ARM core register to VFP system register',
  'fmrx':     '**fmrx** `Rd, sysreg` — Move VFP system register to ARM core register (legacy alias for vmrs)',
  'fmxr':     '**fmxr** `sysreg, Rn` — Move ARM core register to VFP system register (legacy alias for vmsr)',

  // ── System ───────────────────────────────────────────────────────────────────
  'nop':      '**nop** — No operation',
  'wfi':      '**wfi** — Wait for interrupt (low-power stall)',
  'wfe':      '**wfe** — Wait for event',
  'sev':      '**sev** — Send event (wakes a core waiting on WFE)',
  'bkpt':     '**bkpt** `#imm` — Breakpoint: causes DebugMonitor exception or halts debugger',
  'svc':      '**svc** `#imm` — Supervisor call: triggers SVC exception (OS syscall)',
  'dmb':      '**dmb** — Data memory barrier: ensures memory accesses complete before continuing',
  'dsb':      '**dsb** — Data synchronisation barrier: stronger than DMB',
  'isb':      '**isb** — Instruction synchronisation barrier: flushes pipeline',
};
