/**
 * Hover descriptions for Cortex-M33 / Thumb-2 mnemonics.
 * Keys are lowercase mnemonic strings. Add entries freely.
 */
export type HoverEntry = string | ((ops: string[]) => string);
export const hoverData: Record<string, HoverEntry> = {
  // ── Stack ────────────────────────────────────────────────────────────────────
  'push':     (ops) => `**push** \`${ops[0]??'?'}\` — Push ${ops[0]??'?'} onto stack`,
  'pop':      (ops) => `**pop** \`${ops[0]??'?'}\` — Pop from stack into ${ops[0]??'?'}`,

  // ── Data movement ────────────────────────────────────────────────────────────
  'mov':      (ops) => `**mov** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Move: \`${ops[0]??'?'} = ${ops[1]??'?'}\` (does not update flags)`,
  'movs':     (ops) => `**movs** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Move and update N/Z flags: \`${ops[0]??'?'} = ${ops[1]??'?'}\``,
  'movw':     (ops) => `**movw** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Move 16-bit immediate into lower half of ${ops[0]??'?'} (zero-extends)`,
  'movt':     (ops) => `**movt** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Move 16-bit immediate into upper half of ${ops[0]??'?'} (lower half unchanged)`,
  'msr':      (ops) => `**msr** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Move to special register: \`${ops[0]??'?'} = ${ops[1]??'?'}\``,
  'mrs':      (ops) => `**mrs** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Move from special register: \`${ops[0]??'?'} = ${ops[1]??'?'}\``,
  'vmov':     (ops) => `**vmov** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Move between ARM core registers and VFP single-precision registers`,
  'vmovs':    (ops) => `**vmovs** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Copy VFP single-precision register`,
  'vmovd':    (ops) => `**vmovd** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Copy VFP double-precision register`,

  // ── Loads ────────────────────────────────────────────────────────────────────
  'ldr':      (ops) => `**ldr** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Load 32-bit word: \`${ops[0]??'?'} = mem${ops[1]??'?'}\``,
  'ldrb':     (ops) => `**ldrb** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Load byte (zero-extended): \`${ops[0]??'?'} = mem${ops[1]??'?'}\``,
  'ldrh':     (ops) => `**ldrh** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Load halfword (zero-extended): \`${ops[0]??'?'} = mem${ops[1]??'?'}\``,
  'ldrsb':    (ops) => `**ldrsb** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Load byte (sign-extended): \`${ops[0]??'?'} = mem${ops[1]??'?'}\``,
  'ldrsh':    (ops) => `**ldrsh** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Load halfword (sign-extended): \`${ops[0]??'?'} = mem${ops[1]??'?'}\``,
  'ldr.w':    (ops) => `**ldr.w** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — 32-bit Thumb-2 load: \`${ops[0]??'?'} = mem${ops[1]??'?'}\``,
  'ldrb.w':   (ops) => `**ldrb.w** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — 32-bit Thumb-2 load byte (zero-extended)`,
  'ldrh.w':   (ops) => `**ldrh.w** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — 32-bit Thumb-2 load halfword (zero-extended)`,
  'ldm':      (ops) => `**ldm** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Load multiple registers from consecutive addresses`,
  'ldmia':    (ops) => `**ldmia** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Load multiple, increment after (${ops[0]??'?'} updated)`,
  'vldr':     (ops) => `**vldr** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Load VFP single-precision register from memory`,
  'vldm':     (ops) => `**vldm** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Load multiple VFP registers`,

  // ── Stores ───────────────────────────────────────────────────────────────────
  'str':      (ops) => `**str** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Store 32-bit word: \`mem${ops[1]??'?'} = ${ops[0]??'?'}\``,
  'strb':     (ops) => `**strb** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Store byte: \`mem${ops[1]??'?'} = ${ops[0]??'?'}\``,
  'strh':     (ops) => `**strh** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Store halfword: \`mem${ops[1]??'?'} = ${ops[0]??'?'}\``,
  'str.w':    (ops) => `**str.w** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — 32-bit Thumb-2 store: \`mem${ops[1]??'?'} = ${ops[0]??'?'}\``,
  'strb.w':   (ops) => `**strb.w** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — 32-bit Thumb-2 store byte`,
  'strh.w':   (ops) => `**strh.w** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — 32-bit Thumb-2 store halfword`,
  'stm':      (ops) => `**stm** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Store multiple registers`,
  'stmia':    (ops) => `**stmia** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Store multiple, increment after`,
  'stmdb':    (ops) => `**stmdb** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Store multiple, decrement before`,
  'vstr':     (ops) => `**vstr** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Store VFP single-precision register to memory`,
  'vstm':     (ops) => `**vstm** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Store multiple VFP registers`,
  'vpush':    (ops) => `**vpush** \`${ops[0]??'?'}\` — Push VFP registers ${ops[0]??'?'} onto stack`,
  'vpop':     (ops) => `**vpop** \`${ops[0]??'?'}\` — Pop VFP registers from stack into ${ops[0]??'?'}`,

  // ── Arithmetic ───────────────────────────────────────────────────────────────
  'add':      (ops) => `**add** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Add: \`${ops[0]??'?'} = ${ops[1]??'?'} + ${ops[2]??'?'}\``,
  'adds':     (ops) => `**adds** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??ops[1]??'?'}\` — Add and update N/Z/C/V flags: \`${ops[0]??'?'} = ${ops[1]??'?'} + ${ops[2]??ops[1]??'?'}\``,
  'add.w':    (ops) => `**add.w** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — 32-bit Thumb-2 add: \`${ops[0]??'?'} = ${ops[1]??'?'} + ${ops[2]??'?'}\``,
  'sub':      (ops) => `**sub** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Subtract: \`${ops[0]??'?'} = ${ops[1]??'?'} - ${ops[2]??'?'}\``,
  'subs':     (ops) => `**subs** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Subtract and update flags: \`${ops[0]??'?'} = ${ops[1]??'?'} - ${ops[2]??'?'}\``,
  'sub.w':    (ops) => `**sub.w** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — 32-bit Thumb-2 subtract`,
  'rsb':      (ops) => `**rsb** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Reverse subtract: \`${ops[0]??'?'} = ${ops[2]??'?'} - ${ops[1]??'?'}\``,
  'rsbs':     (ops) => `**rsbs** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Reverse subtract and update flags: \`${ops[0]??'?'} = ${ops[2]??'?'} - ${ops[1]??'?'}\``,
  'adc':      (ops) => `**adc** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Add with carry: \`${ops[0]??'?'} = ${ops[1]??'?'} + ${ops[2]??'?'} + C\``,
  'adcs':     (ops) => `**adcs** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Add with carry, update flags`,
  'sbc':      (ops) => `**sbc** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Subtract with carry: \`${ops[0]??'?'} = ${ops[1]??'?'} - ${ops[2]??'?'} - ~C\``,
  'sbcs':     (ops) => `**sbcs** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Subtract with carry, update flags`,
  'mul':      (ops) => `**mul** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Multiply (lower 32 bits): \`${ops[0]??'?'} = ${ops[1]??'?'} × ${ops[2]??'?'}\``,
  'mla':      (ops) => `**mla** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}, ${ops[3]??'?'}\` — Multiply-accumulate: \`${ops[0]??'?'} = ${ops[3]??'?'} + ${ops[1]??'?'}×${ops[2]??'?'}\``,
  'mls':      (ops) => `**mls** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}, ${ops[3]??'?'}\` — Multiply-subtract: \`${ops[0]??'?'} = ${ops[3]??'?'} - ${ops[1]??'?'}×${ops[2]??'?'}\``,
  'umull':    (ops) => `**umull** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}, ${ops[3]??'?'}\` — Unsigned multiply long: \`{${ops[1]??'?'}:${ops[0]??'?'}} = ${ops[2]??'?'} × ${ops[3]??'?'}\``,
  'smull':    (ops) => `**smull** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}, ${ops[3]??'?'}\` — Signed multiply long: \`{${ops[1]??'?'}:${ops[0]??'?'}} = ${ops[2]??'?'} × ${ops[3]??'?'}\``,
  'sdiv':     (ops) => `**sdiv** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Signed divide: \`${ops[0]??'?'} = ${ops[1]??'?'} / ${ops[2]??'?'}\``,
  'udiv':     (ops) => `**udiv** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Unsigned divide: \`${ops[0]??'?'} = ${ops[1]??'?'} / ${ops[2]??'?'}\``,

  // ── Logical / Shift ──────────────────────────────────────────────────────────
  'and':      (ops) => `**and** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Bitwise AND: \`${ops[0]??'?'} = ${ops[1]??'?'} & ${ops[2]??'?'}\``,
  'ands':     (ops) => `**ands** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Bitwise AND, update flags`,
  'orr':      (ops) => `**orr** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Bitwise OR: \`${ops[0]??'?'} = ${ops[1]??'?'} | ${ops[2]??'?'}\``,
  'orrs':     (ops) => `**orrs** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Bitwise OR, update flags`,
  'eor':      (ops) => `**eor** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Bitwise XOR: \`${ops[0]??'?'} = ${ops[1]??'?'} ^ ${ops[2]??'?'}\``,
  'eors':     (ops) => `**eors** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Bitwise XOR, update flags`,
  'bic':      (ops) => `**bic** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Bit clear: \`${ops[0]??'?'} = ${ops[1]??'?'} & ~${ops[2]??'?'}\``,
  'bics':     (ops) => `**bics** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Bit clear, update flags`,
  'mvn':      (ops) => `**mvn** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Bitwise NOT: \`${ops[0]??'?'} = ~${ops[1]??'?'}\``,
  'mvns':     (ops) => `**mvns** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Bitwise NOT, update flags`,
  'lsl':      (ops) => `**lsl** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Logical shift left: \`${ops[0]??'?'} = ${ops[1]??'?'} << ${ops[2]??'?'}\``,
  'lsls':     (ops) => `**lsls** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Logical shift left, update flags`,
  'lsr':      (ops) => `**lsr** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Logical shift right: \`${ops[0]??'?'} = ${ops[1]??'?'} >> ${ops[2]??'?'}\``,
  'lsrs':     (ops) => `**lsrs** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Logical shift right, update flags`,
  'asr':      (ops) => `**asr** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Arithmetic shift right (sign-extending)`,
  'asrs':     (ops) => `**asrs** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Arithmetic shift right, update flags`,
  'ror':      (ops) => `**ror** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Rotate right`,
  'rors':     (ops) => `**rors** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Rotate right, update flags`,
  'rrx':      (ops) => `**rrx** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Rotate right extended through carry`,
  'clz':      (ops) => `**clz** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Count leading zeros: \`${ops[0]??'?'} = clz(${ops[1]??'?'})\``,
  'rev':      (ops) => `**rev** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Reverse byte order: \`${ops[0]??'?'} = bswap(${ops[1]??'?'})\``,
  'rev16':    (ops) => `**rev16** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Reverse bytes in each halfword`,
  'revsh':    (ops) => `**revsh** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Reverse bytes in lower halfword and sign-extend`,
  'sxth':     (ops) => `**sxth** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Sign-extend halfword: \`${ops[0]??'?'} = sign_ext16(${ops[1]??'?'})\``,
  'sxtb':     (ops) => `**sxtb** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Sign-extend byte: \`${ops[0]??'?'} = sign_ext8(${ops[1]??'?'})\``,
  'uxth':     (ops) => `**uxth** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Zero-extend halfword: \`${ops[0]??'?'} = ${ops[1]??'?'} & 0xFFFF\``,
  'uxtb':     (ops) => `**uxtb** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Zero-extend byte: \`${ops[0]??'?'} = ${ops[1]??'?'} & 0xFF\``,
  'uxtab':    (ops) => `**uxtab** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Zero-extend byte and add`,
  'sxtab':    (ops) => `**sxtab** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Sign-extend byte and add`,
  'pld':      (ops) => `**pld** \`${ops[0]??'?'}\` — Preload data hint (prefetch cache line)`,

  // ── Compare / Test ───────────────────────────────────────────────────────────
  'cmp':      (ops) => `**cmp** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compare: set flags for \`${ops[0]??'?'} - ${ops[1]??'?'}\``,
  'cmn':      (ops) => `**cmn** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compare negative: flags from \`${ops[0]??'?'} + ${ops[1]??'?'}\``,
  'tst':      (ops) => `**tst** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Test bits: N/Z flags from \`${ops[0]??'?'} & ${ops[1]??'?'}\``,
  'teq':      (ops) => `**teq** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Test equivalence: N/Z flags from \`${ops[0]??'?'} ^ ${ops[1]??'?'}\``,

  // ── Branches ─────────────────────────────────────────────────────────────────
  'b':        (ops) => `**b** \`${ops[0]??'?'}\` — Unconditional branch to ${ops[0]??'?'}`,
  'b.n':      (ops) => `**b.n** \`${ops[0]??'?'}\` — Narrow (16-bit) unconditional branch to ${ops[0]??'?'}`,
  'b.w':      (ops) => `**b.w** \`${ops[0]??'?'}\` — Wide (32-bit) unconditional branch to ${ops[0]??'?'}`,
  'bl':       (ops) => `**bl** \`${ops[0]??'?'}\` — Branch with link: \`lr = next instruction\`, jump to ${ops[0]??'?'}`,
  'blx':      (ops) => `**blx** \`${ops[0]??'?'}\` — Branch with link and exchange to ${ops[0]??'?'}`,
  'bx':       (ops) => `**bx** \`${ops[0]??'?'}\` — Branch and exchange: jump to ${ops[0]??'?'}, bit[0] selects Thumb/ARM`,
  'beq':      (ops) => `**beq** \`${ops[0]??'?'}\` — Branch to ${ops[0]??'?'} if Z == 1 (equal)`,
  'bne':      (ops) => `**bne** \`${ops[0]??'?'}\` — Branch to ${ops[0]??'?'} if Z == 0 (not equal)`,
  'bcs':      (ops) => `**bcs** \`${ops[0]??'?'}\` — Branch to ${ops[0]??'?'} if C == 1 (carry set)`,
  'bcc':      (ops) => `**bcc** \`${ops[0]??'?'}\` — Branch to ${ops[0]??'?'} if C == 0 (carry clear)`,
  'bmi':      (ops) => `**bmi** \`${ops[0]??'?'}\` — Branch to ${ops[0]??'?'} if N == 1 (negative)`,
  'bpl':      (ops) => `**bpl** \`${ops[0]??'?'}\` — Branch to ${ops[0]??'?'} if N == 0 (non-negative)`,
  'bvs':      (ops) => `**bvs** \`${ops[0]??'?'}\` — Branch to ${ops[0]??'?'} if V == 1 (overflow)`,
  'bvc':      (ops) => `**bvc** \`${ops[0]??'?'}\` — Branch to ${ops[0]??'?'} if V == 0 (no overflow)`,
  'bge':      (ops) => `**bge** \`${ops[0]??'?'}\` — Branch to ${ops[0]??'?'} if N == V (signed ≥)`,
  'blt':      (ops) => `**blt** \`${ops[0]??'?'}\` — Branch to ${ops[0]??'?'} if N ≠ V (signed <)`,
  'bgt':      (ops) => `**bgt** \`${ops[0]??'?'}\` — Branch to ${ops[0]??'?'} if Z == 0 and N == V (signed >)`,
  'ble':      (ops) => `**ble** \`${ops[0]??'?'}\` — Branch to ${ops[0]??'?'} if Z == 1 or N ≠ V (signed ≤)`,
  'bhi':      (ops) => `**bhi** \`${ops[0]??'?'}\` — Branch to ${ops[0]??'?'} if C == 1 and Z == 0 (unsigned higher)`,
  'bls':      (ops) => `**bls** \`${ops[0]??'?'}\` — Branch to ${ops[0]??'?'} if C == 0 or Z == 1 (unsigned lower or same)`,
  'cbz':      (ops) => `**cbz** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compare and branch if ${ops[0]??'?'} == 0`,
  'cbnz':     (ops) => `**cbnz** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compare and branch if ${ops[0]??'?'} ≠ 0`,
  'it':       (ops) => `**it** \`${ops[0]??'?'}\` — If-Then block: next instruction is conditional on ${ops[0]??'?'}`,
  'ite':      (ops) => `**ite** \`${ops[0]??'?'}\` — If-Then-Else block: 2 conditional instructions`,
  'itt':      (ops) => `**itt** \`${ops[0]??'?'}\` — If-Then-Then: 2 instructions with same condition`,
  'itee':     (ops) => `**itee** \`${ops[0]??'?'}\` — If-Then-Else-Else: 3 conditional instructions`,

  // ── VFP / FPU ────────────────────────────────────────────────────────────────
  'vadd':     (ops) => `**vadd** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — VFP add: \`${ops[0]??'?'} = ${ops[1]??'?'} + ${ops[2]??'?'}\``,
  'vsub':     (ops) => `**vsub** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — VFP subtract: \`${ops[0]??'?'} = ${ops[1]??'?'} - ${ops[2]??'?'}\``,
  'vmul':     (ops) => `**vmul** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — VFP multiply: \`${ops[0]??'?'} = ${ops[1]??'?'} × ${ops[2]??'?'}\``,
  'vdiv':     (ops) => `**vdiv** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — VFP divide: \`${ops[0]??'?'} = ${ops[1]??'?'} / ${ops[2]??'?'}\``,
  'vcmp':     (ops) => `**vcmp** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — VFP compare ${ops[0]??'?'} vs ${ops[1]??'?'}, result written to FPSCR`,
  'vcmpe':    (ops) => `**vcmpe** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — VFP compare with invalid operation on NaN`,
  'vcvt':     (ops) => `**vcvt** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — VFP convert between integer and floating-point`,
  'vcvtr':    (ops) => `**vcvtr** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — VFP convert with rounding`,
  'vsqrt':    (ops) => `**vsqrt** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — VFP square root: \`${ops[0]??'?'} = sqrt(${ops[1]??'?'})\``,
  'vabs':     (ops) => `**vabs** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — VFP absolute value: \`${ops[0]??'?'} = |${ops[1]??'?'}|\``,
  'vneg':     (ops) => `**vneg** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — VFP negate: \`${ops[0]??'?'} = -${ops[1]??'?'}\``,
  'vmrs':     (ops) => `**vmrs** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Move VFP system register ${ops[1]??'?'} to ARM core register ${ops[0]??'?'}`,
  'vmsr':     (ops) => `**vmsr** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Move ARM core register ${ops[1]??'?'} to VFP system register ${ops[0]??'?'}`,
  'fmrx':     (ops) => `**fmrx** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Move VFP system register to ARM core register (legacy alias for vmrs)`,
  'fmxr':     (ops) => `**fmxr** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Move ARM core register to VFP system register (legacy alias for vmsr)`,

  // ── System ───────────────────────────────────────────────────────────────────
  'nop':      '**nop** — No operation',
  'wfi':      '**wfi** — Wait for interrupt (low-power stall)',
  'wfe':      '**wfe** — Wait for event',
  'sev':      '**sev** — Send event (wakes a core waiting on WFE)',
  'bkpt':     (ops) => `**bkpt** \`${ops[0]??'?'}\` — Breakpoint: causes DebugMonitor exception or halts debugger`,
  'svc':      (ops) => `**svc** \`${ops[0]??'?'}\` — Supervisor call: triggers SVC exception (OS syscall)`,
  'dmb':      '**dmb** — Data memory barrier: ensures memory accesses complete before continuing',
  'dsb':      '**dsb** — Data synchronisation barrier: stronger than DMB',
  'isb':      '**isb** — Instruction synchronisation barrier: flushes pipeline',
};
