import { HoverEntry, escOp, escMd, op } from '../types';

export const hoverData: Record<string, HoverEntry> = {
  // ── Arithmetic ───────────────────────────────────────────────────────────────
  'add':        (ops) => `**add** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Integer addition: \`${escOp(ops,0)} = ${escOp(ops,1)} + ${escOp(ops,2)}\``,
  'addi':       (ops) => `**addi** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Add immediate: \`${escOp(ops,0)} = ${escOp(ops,1)} + sign_ext(${escOp(ops,2)})\``,
  'sub':        (ops) => `**sub** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Integer subtraction: \`${escOp(ops,0)} = ${escOp(ops,1)} - ${escOp(ops,2)}\``,
  'lui':        (ops) => `**lui** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Load upper immediate: \`${escOp(ops,0)} = ${escOp(ops,1)} << 12\` (upper 20 bits)`,
  'auipc':      (ops) => `**auipc** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Add upper immediate to PC: \`${escOp(ops,0)} = PC + (${escOp(ops,1)} << 12)\``,
  'mul':        (ops) => `**mul** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Multiply (lower 32 bits): \`${escOp(ops,0)} = (${escOp(ops,1)} × ${escOp(ops,2)})[31:0]\``,
  'mulh':       (ops) => `**mulh** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Multiply high signed×signed: \`${escOp(ops,0)} = (${escOp(ops,1)} × ${escOp(ops,2)})[63:32]\``,
  'mulhu':      (ops) => `**mulhu** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Multiply high unsigned×unsigned`,
  'mulhsu':     (ops) => `**mulhsu** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Multiply high signed×unsigned`,
  'div':        (ops) => `**div** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Signed integer divide: \`${escOp(ops,0)} = ${escOp(ops,1)} / ${escOp(ops,2)}\``,
  'divu':       (ops) => `**divu** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Unsigned integer divide: \`${escOp(ops,0)} = ${escOp(ops,1)} / ${escOp(ops,2)}\``,
  'rem':        (ops) => `**rem** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Signed remainder: \`${escOp(ops,0)} = ${escOp(ops,1)} % ${escOp(ops,2)}\``,
  'remu':       (ops) => `**remu** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Unsigned remainder: \`${escOp(ops,0)} = ${escOp(ops,1)} % ${escOp(ops,2)}\``,

  // ── Logical / Shift ──────────────────────────────────────────────────────────
  'and':        (ops) => `**and** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Bitwise AND`,
  'andi':       (ops) => `**andi** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Bitwise AND with immediate`,
  'or':         (ops) => `**or** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Bitwise OR`,
  'ori':        (ops) => `**ori** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Bitwise OR with immediate`,
  'xor':        (ops) => `**xor** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Bitwise XOR`,
  'xori':       (ops) => `**xori** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Bitwise XOR with immediate`,
  'sll':        (ops) => `**sll** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Shift left logical by register`,
  'slli':       (ops) => `**slli** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Shift left logical by immediate`,
  'srl':        (ops) => `**srl** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Shift right logical by register`,
  'srli':       (ops) => `**srli** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Shift right logical by immediate`,
  'sra':        (ops) => `**sra** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Shift right arithmetic by register`,
  'srai':       (ops) => `**srai** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Shift right arithmetic (sign-extending) by immediate`,
  'slt':        (ops) => `**slt** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Set if less than (signed): \`${escOp(ops,0)} = ${escOp(ops,1)} < ${escOp(ops,2)} ? 1 : 0\``,
  'sltu':       (ops) => `**sltu** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Set if less than unsigned`,
  'slti':       (ops) => `**slti** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Set if less than immediate (signed)`,
  'sltiu':      (ops) => `**sltiu** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Set if less than immediate unsigned`,

  // ── Loads / Stores ───────────────────────────────────────────────────────────
  'lw':         (ops) => `**lw** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Load 32-bit word: \`${escOp(ops,0)} = mem[${escOp(ops,1)}]\``,
  'lh':         (ops) => `**lh** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Load 16-bit halfword (sign-extended): \`${escOp(ops,0)} = mem[${escOp(ops,1)}]\``,
  'lhu':        (ops) => `**lhu** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Load 16-bit halfword (zero-extended): \`${escOp(ops,0)} = mem[${escOp(ops,1)}]\``,
  'lb':         (ops) => `**lb** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Load byte (sign-extended): \`${escOp(ops,0)} = mem[${escOp(ops,1)}]\``,
  'lbu':        (ops) => `**lbu** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Load byte (zero-extended): \`${escOp(ops,0)} = mem[${escOp(ops,1)}]\``,
  'sw':         (ops) => `**sw** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Store 32-bit word: \`mem[${escOp(ops,1)}] = ${escOp(ops,0)}\``,
  'sh':         (ops) => `**sh** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Store 16-bit halfword: \`mem[${escOp(ops,1)}] = ${escOp(ops,0)}\``,
  'sb':         (ops) => `**sb** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Store byte: \`mem[${escOp(ops,1)}] = ${escOp(ops,0)}\``,

  // ── Branches / Jumps ────────────────────────────────────────────────────────
  'beq':        (ops) => `**beq** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Branch if equal: if \`${escOp(ops,0)} == ${escOp(ops,1)}\` jump to ${escMd(op(ops,2))}`,
  'bne':        (ops) => `**bne** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Branch if not equal: if \`${escOp(ops,0)} ≠ ${escOp(ops,1)}\` jump to ${escMd(op(ops,2))}`,
  'blt':        (ops) => `**blt** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Branch if less than (signed): if \`${escOp(ops,0)} < ${escOp(ops,1)}\` jump to ${escMd(op(ops,2))}`,
  'bge':        (ops) => `**bge** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Branch if ≥ (signed): if \`${escOp(ops,0)} ≥ ${escOp(ops,1)}\` jump to ${escMd(op(ops,2))}`,
  'bltu':       (ops) => `**bltu** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Branch if less than (unsigned): if \`${escOp(ops,0)} < ${escOp(ops,1)}\` jump to ${escMd(op(ops,2))}`,
  'bgeu':       (ops) => `**bgeu** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Branch if ≥ (unsigned): if \`${escOp(ops,0)} ≥ ${escOp(ops,1)}\` jump to ${escMd(op(ops,2))}`,
  'jal':        (ops) => `**jal** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Jump and link: \`${escOp(ops,0)} = PC+4\`, jump to ${escMd(op(ops,1))}`,
  'jalr':       (ops) => `**jalr** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Jump and link register: \`${escOp(ops,0)} = PC+4; PC = ${escOp(ops,1)}\``,
  'ret':        '**ret** — Return from function (pseudo: `jalr x0, ra, 0`)',
  'j':          (ops) => `**j** \`${escOp(ops,0)}\` — Unconditional jump (pseudo: \`jal x0, ${escOp(ops,0)}\`)`,
  'jr':         (ops) => `**jr** \`${escOp(ops,0)}\` — Jump to register (pseudo: \`jalr x0, ${escOp(ops,0)}, 0\`)`,
  'beqz':       (ops) => `**beqz** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Branch if ${escMd(op(ops,0))} == 0 (pseudo: \`beq ${escOp(ops,0)}, x0, ${escOp(ops,1)}\`)`,
  'bnez':       (ops) => `**bnez** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Branch if ${escMd(op(ops,0))} ≠ 0 (pseudo: \`bne ${escOp(ops,0)}, x0, ${escOp(ops,1)}\`)`,
  'li':         (ops) => `**li** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Load immediate: \`${escOp(ops,0)} = ${escOp(ops,1)}\` (pseudo — assembler expands to lui+addi)`,

  // ── Atomics ──────────────────────────────────────────────────────────────────
  'lr.w':       (ops) => `**lr.w** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Load-reserved word (begin atomic sequence)`,
  'sc.w':       (ops) => `**sc.w** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Store-conditional word (complete atomic sequence)`,
  'amoswap.w':  (ops) => `**amoswap.w** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Atomic swap: \`${escOp(ops,0)} = *${escOp(ops,2)}; *${escOp(ops,2)} = ${escOp(ops,1)}\``,
  'amoadd.w':   (ops) => `**amoadd.w** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Atomic fetch-and-add`,
  'amoxor.w':   (ops) => `**amoxor.w** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Atomic fetch-and-XOR`,
  'amoand.w':   (ops) => `**amoand.w** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Atomic fetch-and-AND`,
  'amoor.w':    (ops) => `**amoor.w** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Atomic fetch-and-OR`,
  'amomin.w':   (ops) => `**amomin.w** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Atomic fetch-and-min (signed)`,
  'amomax.w':   (ops) => `**amomax.w** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Atomic fetch-and-max (signed)`,
  'amominu.w':  (ops) => `**amominu.w** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Atomic fetch-and-min (unsigned)`,
  'amomaxu.w':  (ops) => `**amomaxu.w** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Atomic fetch-and-max (unsigned)`,

  // ── CSR / System ─────────────────────────────────────────────────────────────
  'csrw':       (ops) => `**csrw** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Write ${escMd(op(ops,1))} to CSR ${escMd(op(ops,0))} (pseudo: \`csrrw x0, ${escOp(ops,0)}, ${escOp(ops,1)}\`)`,
  'csrr':       (ops) => `**csrr** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Read CSR ${escMd(op(ops,1))} into ${escMd(op(ops,0))} (pseudo: \`csrrs ${escOp(ops,0)}, ${escOp(ops,1)}, x0\`)`,
  'csrwi':      (ops) => `**csrwi** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Write immediate ${escMd(op(ops,1))} to CSR ${escMd(op(ops,0))}`,
  'csrrw':      (ops) => `**csrrw** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Atomic CSR read-write: \`${escOp(ops,0)} = CSR[${escOp(ops,1)}]; CSR[${escOp(ops,1)}] = ${escOp(ops,2)}\``,
  'csrrs':      (ops) => `**csrrs** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Atomic CSR read and set bits`,
  'csrrc':      (ops) => `**csrrc** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Atomic CSR read and clear bits`,
  'csrrwi':     (ops) => `**csrrwi** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Atomic CSR read-write with immediate`,
  'csrrsi':     (ops) => `**csrrsi** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Atomic CSR read and set bits with immediate`,
  'csrrci':     (ops) => `**csrrci** \`${escOp(ops,0)}, ${escOp(ops,1)}, ${escOp(ops,2)}\` — Atomic CSR read and clear bits with immediate`,
  'mret':       '**mret** — Return from machine-mode trap (restores PC from mepc, mode from mstatus)',
  'sret':       (_ops) => `**sret** — Return from supervisor-mode trap`,
  'wfi':        '**wfi** — Wait for interrupt (low-power stall until interrupt pending)',
  'ecall':      '**ecall** — Environment call (trap to OS / firmware)',
  'ebreak':     '**ebreak** — Trigger breakpoint trap',
  'fence':      '**fence** `pred, succ` — Memory/IO ordering fence',

  // ── C Extension (compressed 16-bit) ──────────────────────────────────────────
  'c.addi':     (ops) => `**c.addi** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Compressed: \`${escOp(ops,0)} = ${escOp(ops,0)} + sign_ext(${escOp(ops,1)})\` (imm ≠ 0)`,
  'c.addi16sp': (ops) => `**c.addi16sp** \`${escOp(ops,0)}\` — Compressed: \`sp = sp + sign_ext(${escOp(ops,0)}*16)\``,
  'c.addi4spn': (ops) => `**c.addi4spn** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Compressed: \`${escOp(ops,0)} = sp + zero_ext(${escOp(ops,1)}*4)\``,
  'c.li':       (ops) => `**c.li** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Compressed load immediate: \`${escOp(ops,0)} = ${escOp(ops,1)}\``,
  'c.lui':      (ops) => `**c.lui** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Compressed load upper immediate`,
  'c.mv':       (ops) => `**c.mv** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Compressed move: \`${escOp(ops,0)} = ${escOp(ops,1)}\``,
  'c.add':      (ops) => `**c.add** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Compressed add: \`${escOp(ops,0)} = ${escOp(ops,0)} + ${escOp(ops,1)}\``,
  'c.sub':      (ops) => `**c.sub** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Compressed subtract: \`${escOp(ops,0)} = ${escOp(ops,0)} - ${escOp(ops,1)}\``,
  'c.and':      (ops) => `**c.and** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Compressed bitwise AND`,
  'c.or':       (ops) => `**c.or** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Compressed bitwise OR`,
  'c.xor':      (ops) => `**c.xor** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Compressed bitwise XOR`,
  'c.slli':     (ops) => `**c.slli** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Compressed shift left logical`,
  'c.srli':     (ops) => `**c.srli** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Compressed shift right logical`,
  'c.srai':     (ops) => `**c.srai** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Compressed shift right arithmetic`,
  'c.andi':     (ops) => `**c.andi** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Compressed AND with immediate`,
  'c.lw':       (ops) => `**c.lw** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Compressed load word: \`${escOp(ops,0)} = mem[${escOp(ops,1)}]\``,
  'c.sw':       (ops) => `**c.sw** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Compressed store word: \`mem[${escOp(ops,1)}] = ${escOp(ops,0)}\``,
  'c.lwsp':     (ops) => `**c.lwsp** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Compressed load word from stack pointer`,
  'c.swsp':     (ops) => `**c.swsp** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Compressed store word to stack pointer`,
  'c.j':        (ops) => `**c.j** \`${escOp(ops,0)}\` — Compressed unconditional jump`,
  'c.jr':       (ops) => `**c.jr** \`${escOp(ops,0)}\` — Compressed jump to register`,
  'c.jal':      (ops) => `**c.jal** \`${escOp(ops,0)}\` — Compressed jump and link (RV32 only)`,
  'c.jalr':     (ops) => `**c.jalr** \`${escOp(ops,0)}\` — Compressed jump and link register`,
  'c.beqz':     (ops) => `**c.beqz** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Compressed branch if ${escMd(op(ops,0))} == 0`,
  'c.bnez':     (ops) => `**c.bnez** \`${escOp(ops,0)}, ${escOp(ops,1)}\` — Compressed branch if ${escMd(op(ops,0))} ≠ 0`,
  'c.ebreak':   '**c.ebreak** — Compressed breakpoint trap',
};
