/**
 * Hover descriptions for RISC-V (RV32IMAC + Zicsr) mnemonics.
 * Keys are lowercase mnemonic strings. Add entries freely — the table is the only thing to maintain.
 */
export const hoverData: Record<string, string> = {
  // ── Arithmetic ───────────────────────────────────────────────────────────────
  'add':        '**add** `rd, rs1, rs2` — Integer addition: `rd = rs1 + rs2`',
  'addi':       '**addi** `rd, rs1, imm` — Add immediate: `rd = rs1 + sign_ext(imm12)`',
  'sub':        '**sub** `rd, rs1, rs2` — Integer subtraction: `rd = rs1 - rs2`',
  'lui':        '**lui** `rd, imm` — Load upper immediate: `rd = imm << 12` (upper 20 bits)',
  'auipc':      '**auipc** `rd, imm` — Add upper immediate to PC: `rd = PC + (imm << 12)`',
  'mul':        '**mul** `rd, rs1, rs2` — Multiply (lower 32 bits): `rd = (rs1 × rs2)[31:0]`',
  'mulh':       '**mulh** `rd, rs1, rs2` — Multiply high signed×signed: `rd = (rs1 × rs2)[63:32]`',
  'mulhu':      '**mulhu** `rd, rs1, rs2` — Multiply high unsigned×unsigned',
  'mulhsu':     '**mulhsu** `rd, rs1, rs2` — Multiply high signed×unsigned',
  'div':        '**div** `rd, rs1, rs2` — Signed integer divide: `rd = rs1 / rs2`',
  'divu':       '**divu** `rd, rs1, rs2` — Unsigned integer divide: `rd = rs1 / rs2`',
  'rem':        '**rem** `rd, rs1, rs2` — Signed remainder: `rd = rs1 % rs2`',
  'remu':       '**remu** `rd, rs1, rs2` — Unsigned remainder: `rd = rs1 % rs2`',

  // ── Logical / Shift ──────────────────────────────────────────────────────────
  'and':        '**and** `rd, rs1, rs2` — Bitwise AND',
  'andi':       '**andi** `rd, rs1, imm` — Bitwise AND with immediate',
  'or':         '**or** `rd, rs1, rs2` — Bitwise OR',
  'ori':        '**ori** `rd, rs1, imm` — Bitwise OR with immediate',
  'xor':        '**xor** `rd, rs1, rs2` — Bitwise XOR',
  'xori':       '**xori** `rd, rs1, imm` — Bitwise XOR with immediate',
  'sll':        '**sll** `rd, rs1, rs2` — Shift left logical by register',
  'slli':       '**slli** `rd, rs1, shamt` — Shift left logical by immediate',
  'srl':        '**srl** `rd, rs1, rs2` — Shift right logical by register',
  'srli':       '**srli** `rd, rs1, shamt` — Shift right logical by immediate',
  'sra':        '**sra** `rd, rs1, rs2` — Shift right arithmetic by register',
  'srai':       '**srai** `rd, rs1, shamt` — Shift right arithmetic (sign-extending) by immediate',
  'slt':        '**slt** `rd, rs1, rs2` — Set if less than (signed): `rd = rs1 < rs2 ? 1 : 0`',
  'sltu':       '**sltu** `rd, rs1, rs2` — Set if less than unsigned',
  'slti':       '**slti** `rd, rs1, imm` — Set if less than immediate (signed)',
  'sltiu':      '**sltiu** `rd, rs1, imm` — Set if less than immediate unsigned',

  // ── Loads / Stores ───────────────────────────────────────────────────────────
  'lw':         '**lw** `rd, imm(rs1)` — Load 32-bit word from memory',
  'lh':         '**lh** `rd, imm(rs1)` — Load 16-bit halfword (sign-extended)',
  'lhu':        '**lhu** `rd, imm(rs1)` — Load 16-bit halfword (zero-extended)',
  'lb':         '**lb** `rd, imm(rs1)` — Load byte (sign-extended)',
  'lbu':        '**lbu** `rd, imm(rs1)` — Load byte (zero-extended)',
  'sw':         '**sw** `rs2, imm(rs1)` — Store 32-bit word to memory',
  'sh':         '**sh** `rs2, imm(rs1)` — Store 16-bit halfword to memory',
  'sb':         '**sb** `rs2, imm(rs1)` — Store byte to memory',

  // ── Branches / Jumps ────────────────────────────────────────────────────────
  'beq':        '**beq** `rs1, rs2, offset` — Branch if rs1 == rs2',
  'bne':        '**bne** `rs1, rs2, offset` — Branch if rs1 ≠ rs2',
  'blt':        '**blt** `rs1, rs2, offset` — Branch if rs1 < rs2 (signed)',
  'bge':        '**bge** `rs1, rs2, offset` — Branch if rs1 ≥ rs2 (signed)',
  'bltu':       '**bltu** `rs1, rs2, offset` — Branch if rs1 < rs2 (unsigned)',
  'bgeu':       '**bgeu** `rs1, rs2, offset` — Branch if rs1 ≥ rs2 (unsigned)',
  'jal':        '**jal** `rd, offset` — Jump and link: `rd = PC+4; PC = PC + offset`',
  'jalr':       '**jalr** `rd, imm(rs1)` — Jump and link register: `rd = PC+4; PC = rs1 + imm`',
  'ret':        '**ret** — Return from function (pseudo: `jalr x0, ra, 0`)',
  'j':          '**j** `offset` — Unconditional jump (pseudo: `jal x0, offset`)',
  'jr':         '**jr** `rs` — Jump to register (pseudo: `jalr x0, rs, 0`)',
  'beqz':       '**beqz** `rs, offset` — Branch if rs == 0 (pseudo: `beq rs, x0, offset`)',
  'bnez':       '**bnez** `rs, offset` — Branch if rs ≠ 0 (pseudo: `bne rs, x0, offset`)',
  'li':         '**li** `rd, imm` — Load immediate (pseudo — assembler expands to lui+addi)',

  // ── Atomics ──────────────────────────────────────────────────────────────────
  'lr.w':       '**lr.w** `rd, (rs1)` — Load-reserved word (begin atomic sequence)',
  'sc.w':       '**sc.w** `rd, rs2, (rs1)` — Store-conditional word (complete atomic sequence)',
  'amoswap.w':  '**amoswap.w** `rd, rs2, (rs1)` — Atomic swap: `rd = *rs1; *rs1 = rs2`',
  'amoadd.w':   '**amoadd.w** `rd, rs2, (rs1)` — Atomic fetch-and-add',
  'amoxor.w':   '**amoxor.w** `rd, rs2, (rs1)` — Atomic fetch-and-XOR',
  'amoand.w':   '**amoand.w** `rd, rs2, (rs1)` — Atomic fetch-and-AND',
  'amoor.w':    '**amoor.w** `rd, rs2, (rs1)` — Atomic fetch-and-OR',
  'amomin.w':   '**amomin.w** `rd, rs2, (rs1)` — Atomic fetch-and-min (signed)',
  'amomax.w':   '**amomax.w** `rd, rs2, (rs1)` — Atomic fetch-and-max (signed)',
  'amominu.w':  '**amominu.w** `rd, rs2, (rs1)` — Atomic fetch-and-min (unsigned)',
  'amomaxu.w':  '**amomaxu.w** `rd, rs2, (rs1)` — Atomic fetch-and-max (unsigned)',

  // ── CSR / System ─────────────────────────────────────────────────────────────
  'csrw':       '**csrw** `csr, rs` — Write rs to CSR (pseudo: `csrrw x0, csr, rs`)',
  'csrr':       '**csrr** `rd, csr` — Read CSR into rd (pseudo: `csrrs rd, csr, x0`)',
  'csrwi':      '**csrwi** `csr, imm` — Write immediate to CSR',
  'csrrw':      '**csrrw** `rd, csr, rs` — Atomic CSR read-write: `rd = CSR; CSR = rs`',
  'csrrs':      '**csrrs** `rd, csr, rs` — Atomic CSR read and set bits',
  'csrrc':      '**csrrc** `rd, csr, rs` — Atomic CSR read and clear bits',
  'csrrwi':     '**csrrwi** `rd, csr, imm` — Atomic CSR read-write with immediate',
  'csrrsi':     '**csrrsi** `rd, csr, imm` — Atomic CSR read and set bits with immediate',
  'csrrci':     '**csrrci** `rd, csr, imm` — Atomic CSR read and clear bits with immediate',
  'mret':       '**mret** — Return from machine-mode trap (restores PC from mepc, mode from mstatus)',
  'sret':       '**sret** — Return from supervisor-mode trap',
  'wfi':        '**wfi** — Wait for interrupt (low-power stall until interrupt pending)',
  'ecall':      '**ecall** — Environment call (trap to OS / firmware)',
  'ebreak':     '**ebreak** — Trigger breakpoint trap',
  'fence':      '**fence** `pred, succ` — Memory/IO ordering fence',

  // ── C Extension (compressed 16-bit) ──────────────────────────────────────────
  'c.addi':     '**c.addi** `rd, imm` — Compressed: `rd = rd + sign_ext(imm6)` (imm ≠ 0)',
  'c.addi16sp': '**c.addi16sp** `imm` — Compressed: `sp = sp + sign_ext(imm*16)`',
  'c.addi4spn': '**c.addi4spn** `rd, imm` — Compressed: `rd = sp + zero_ext(imm*4)`',
  'c.li':       '**c.li** `rd, imm` — Compressed load immediate',
  'c.lui':      '**c.lui** `rd, imm` — Compressed load upper immediate',
  'c.mv':       '**c.mv** `rd, rs` — Compressed move: `rd = rs`',
  'c.add':      '**c.add** `rd, rs` — Compressed add: `rd = rd + rs`',
  'c.sub':      '**c.sub** `rd, rs` — Compressed subtract: `rd = rd - rs`',
  'c.and':      '**c.and** `rd, rs` — Compressed bitwise AND',
  'c.or':       '**c.or** `rd, rs` — Compressed bitwise OR',
  'c.xor':      '**c.xor** `rd, rs` — Compressed bitwise XOR',
  'c.slli':     '**c.slli** `rd, shamt` — Compressed shift left logical',
  'c.srli':     '**c.srli** `rd, shamt` — Compressed shift right logical',
  'c.srai':     '**c.srai** `rd, shamt` — Compressed shift right arithmetic',
  'c.andi':     '**c.andi** `rd, imm` — Compressed AND with immediate',
  'c.lw':       '**c.lw** `rd, imm(rs1)` — Compressed load word',
  'c.sw':       '**c.sw** `rs2, imm(rs1)` — Compressed store word',
  'c.lwsp':     '**c.lwsp** `rd, imm` — Compressed load word from stack pointer',
  'c.swsp':     '**c.swsp** `rs2, imm` — Compressed store word to stack pointer',
  'c.j':        '**c.j** `offset` — Compressed unconditional jump',
  'c.jr':       '**c.jr** `rs` — Compressed jump to register',
  'c.jal':      '**c.jal** `offset` — Compressed jump and link (RV32 only)',
  'c.jalr':     '**c.jalr** `rs` — Compressed jump and link register',
  'c.beqz':     '**c.beqz** `rs, offset` — Compressed branch if rs == 0',
  'c.bnez':     '**c.bnez** `rs, offset` — Compressed branch if rs ≠ 0',
  'c.ebreak':   '**c.ebreak** — Compressed breakpoint trap',
};
