/**
 * Hover descriptions for RISC-V (RV32IMAC + Zicsr) mnemonics.
 * Keys are lowercase mnemonic strings. Add entries freely — the table is the only thing to maintain.
 */
export type HoverEntry = string | ((ops: string[]) => string);
export const hoverData: Record<string, HoverEntry> = {
  // ── Arithmetic ───────────────────────────────────────────────────────────────
  'add':        (ops) => `**add** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Integer addition: \`${ops[0]??'?'} = ${ops[1]??'?'} + ${ops[2]??'?'}\``,
  'addi':       (ops) => `**addi** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Add immediate: \`${ops[0]??'?'} = ${ops[1]??'?'} + sign_ext(${ops[2]??'?'})\``,
  'sub':        (ops) => `**sub** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Integer subtraction: \`${ops[0]??'?'} = ${ops[1]??'?'} - ${ops[2]??'?'}\``,
  'lui':        (ops) => `**lui** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Load upper immediate: \`${ops[0]??'?'} = ${ops[1]??'?'} << 12\` (upper 20 bits)`,
  'auipc':      (ops) => `**auipc** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Add upper immediate to PC: \`${ops[0]??'?'} = PC + (${ops[1]??'?'} << 12)\``,
  'mul':        (ops) => `**mul** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Multiply (lower 32 bits): \`${ops[0]??'?'} = (${ops[1]??'?'} × ${ops[2]??'?'})[31:0]\``,
  'mulh':       (ops) => `**mulh** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Multiply high signed×signed: \`${ops[0]??'?'} = (${ops[1]??'?'} × ${ops[2]??'?'})[63:32]\``,
  'mulhu':      (ops) => `**mulhu** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Multiply high unsigned×unsigned`,
  'mulhsu':     (ops) => `**mulhsu** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Multiply high signed×unsigned`,
  'div':        (ops) => `**div** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Signed integer divide: \`${ops[0]??'?'} = ${ops[1]??'?'} / ${ops[2]??'?'}\``,
  'divu':       (ops) => `**divu** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Unsigned integer divide: \`${ops[0]??'?'} = ${ops[1]??'?'} / ${ops[2]??'?'}\``,
  'rem':        (ops) => `**rem** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Signed remainder: \`${ops[0]??'?'} = ${ops[1]??'?'} % ${ops[2]??'?'}\``,
  'remu':       (ops) => `**remu** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Unsigned remainder: \`${ops[0]??'?'} = ${ops[1]??'?'} % ${ops[2]??'?'}\``,

  // ── Logical / Shift ──────────────────────────────────────────────────────────
  'and':        (ops) => `**and** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Bitwise AND`,
  'andi':       (ops) => `**andi** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Bitwise AND with immediate`,
  'or':         (ops) => `**or** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Bitwise OR`,
  'ori':        (ops) => `**ori** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Bitwise OR with immediate`,
  'xor':        (ops) => `**xor** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Bitwise XOR`,
  'xori':       (ops) => `**xori** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Bitwise XOR with immediate`,
  'sll':        (ops) => `**sll** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Shift left logical by register`,
  'slli':       (ops) => `**slli** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Shift left logical by immediate`,
  'srl':        (ops) => `**srl** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Shift right logical by register`,
  'srli':       (ops) => `**srli** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Shift right logical by immediate`,
  'sra':        (ops) => `**sra** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Shift right arithmetic by register`,
  'srai':       (ops) => `**srai** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Shift right arithmetic (sign-extending) by immediate`,
  'slt':        (ops) => `**slt** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Set if less than (signed): \`${ops[0]??'?'} = ${ops[1]??'?'} < ${ops[2]??'?'} ? 1 : 0\``,
  'sltu':       (ops) => `**sltu** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Set if less than unsigned`,
  'slti':       (ops) => `**slti** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Set if less than immediate (signed)`,
  'sltiu':      (ops) => `**sltiu** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Set if less than immediate unsigned`,

  // ── Loads / Stores ───────────────────────────────────────────────────────────
  'lw':         (ops) => `**lw** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Load 32-bit word: \`${ops[0]??'?'} = mem[${ops[1]??'?'}]\``,
  'lh':         (ops) => `**lh** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Load 16-bit halfword (sign-extended): \`${ops[0]??'?'} = mem[${ops[1]??'?'}]\``,
  'lhu':        (ops) => `**lhu** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Load 16-bit halfword (zero-extended): \`${ops[0]??'?'} = mem[${ops[1]??'?'}]\``,
  'lb':         (ops) => `**lb** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Load byte (sign-extended): \`${ops[0]??'?'} = mem[${ops[1]??'?'}]\``,
  'lbu':        (ops) => `**lbu** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Load byte (zero-extended): \`${ops[0]??'?'} = mem[${ops[1]??'?'}]\``,
  'sw':         (ops) => `**sw** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Store 32-bit word: \`mem[${ops[1]??'?'}] = ${ops[0]??'?'}\``,
  'sh':         (ops) => `**sh** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Store 16-bit halfword: \`mem[${ops[1]??'?'}] = ${ops[0]??'?'}\``,
  'sb':         (ops) => `**sb** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Store byte: \`mem[${ops[1]??'?'}] = ${ops[0]??'?'}\``,

  // ── Branches / Jumps ────────────────────────────────────────────────────────
  'beq':        (ops) => `**beq** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Branch if equal: if \`${ops[0]??'?'} == ${ops[1]??'?'}\` jump to ${ops[2]??'?'}`,
  'bne':        (ops) => `**bne** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Branch if not equal: if \`${ops[0]??'?'} ≠ ${ops[1]??'?'}\` jump to ${ops[2]??'?'}`,
  'blt':        (ops) => `**blt** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Branch if less than (signed): if \`${ops[0]??'?'} < ${ops[1]??'?'}\` jump to ${ops[2]??'?'}`,
  'bge':        (ops) => `**bge** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Branch if ≥ (signed): if \`${ops[0]??'?'} ≥ ${ops[1]??'?'}\` jump to ${ops[2]??'?'}`,
  'bltu':       (ops) => `**bltu** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Branch if less than (unsigned): if \`${ops[0]??'?'} < ${ops[1]??'?'}\` jump to ${ops[2]??'?'}`,
  'bgeu':       (ops) => `**bgeu** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Branch if ≥ (unsigned): if \`${ops[0]??'?'} ≥ ${ops[1]??'?'}\` jump to ${ops[2]??'?'}`,
  'jal':        (ops) => `**jal** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Jump and link: \`${ops[0]??'?'} = PC+4\`, jump to ${ops[1]??'?'}`,
  'jalr':       (ops) => `**jalr** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Jump and link register: \`${ops[0]??'?'} = PC+4; PC = ${ops[1]??'?'}\``,
  'ret':        '**ret** — Return from function (pseudo: `jalr x0, ra, 0`)',
  'j':          (ops) => `**j** \`${ops[0]??'?'}\` — Unconditional jump (pseudo: \`jal x0, ${ops[0]??'?'}\`)`,
  'jr':         (ops) => `**jr** \`${ops[0]??'?'}\` — Jump to register (pseudo: \`jalr x0, ${ops[0]??'?'}, 0\`)`,
  'beqz':       (ops) => `**beqz** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Branch if ${ops[0]??'?'} == 0 (pseudo: \`beq ${ops[0]??'?'}, x0, ${ops[1]??'?'}\`)`,
  'bnez':       (ops) => `**bnez** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Branch if ${ops[0]??'?'} ≠ 0 (pseudo: \`bne ${ops[0]??'?'}, x0, ${ops[1]??'?'}\`)`,
  'li':         (ops) => `**li** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Load immediate: \`${ops[0]??'?'} = ${ops[1]??'?'}\` (pseudo — assembler expands to lui+addi)`,

  // ── Atomics ──────────────────────────────────────────────────────────────────
  'lr.w':       (ops) => `**lr.w** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Load-reserved word (begin atomic sequence)`,
  'sc.w':       (ops) => `**sc.w** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Store-conditional word (complete atomic sequence)`,
  'amoswap.w':  (ops) => `**amoswap.w** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Atomic swap: \`${ops[0]??'?'} = *${ops[2]??'?'}; *${ops[2]??'?'} = ${ops[1]??'?'}\``,
  'amoadd.w':   (ops) => `**amoadd.w** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Atomic fetch-and-add`,
  'amoxor.w':   (ops) => `**amoxor.w** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Atomic fetch-and-XOR`,
  'amoand.w':   (ops) => `**amoand.w** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Atomic fetch-and-AND`,
  'amoor.w':    (ops) => `**amoor.w** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Atomic fetch-and-OR`,
  'amomin.w':   (ops) => `**amomin.w** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Atomic fetch-and-min (signed)`,
  'amomax.w':   (ops) => `**amomax.w** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Atomic fetch-and-max (signed)`,
  'amominu.w':  (ops) => `**amominu.w** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Atomic fetch-and-min (unsigned)`,
  'amomaxu.w':  (ops) => `**amomaxu.w** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Atomic fetch-and-max (unsigned)`,

  // ── CSR / System ─────────────────────────────────────────────────────────────
  'csrw':       (ops) => `**csrw** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Write ${ops[1]??'?'} to CSR ${ops[0]??'?'} (pseudo: \`csrrw x0, ${ops[0]??'?'}, ${ops[1]??'?'}\`)`,
  'csrr':       (ops) => `**csrr** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Read CSR ${ops[1]??'?'} into ${ops[0]??'?'} (pseudo: \`csrrs ${ops[0]??'?'}, ${ops[1]??'?'}, x0\`)`,
  'csrwi':      (ops) => `**csrwi** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Write immediate ${ops[1]??'?'} to CSR ${ops[0]??'?'}`,
  'csrrw':      (ops) => `**csrrw** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Atomic CSR read-write: \`${ops[0]??'?'} = CSR[${ops[1]??'?'}]; CSR[${ops[1]??'?'}] = ${ops[2]??'?'}\``,
  'csrrs':      (ops) => `**csrrs** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Atomic CSR read and set bits`,
  'csrrc':      (ops) => `**csrrc** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Atomic CSR read and clear bits`,
  'csrrwi':     (ops) => `**csrrwi** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Atomic CSR read-write with immediate`,
  'csrrsi':     (ops) => `**csrrsi** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Atomic CSR read and set bits with immediate`,
  'csrrci':     (ops) => `**csrrci** \`${ops[0]??'?'}, ${ops[1]??'?'}, ${ops[2]??'?'}\` — Atomic CSR read and clear bits with immediate`,
  'mret':       '**mret** — Return from machine-mode trap (restores PC from mepc, mode from mstatus)',
  'sret':       (ops) => `**sret** — Return from supervisor-mode trap`,
  'wfi':        '**wfi** — Wait for interrupt (low-power stall until interrupt pending)',
  'ecall':      '**ecall** — Environment call (trap to OS / firmware)',
  'ebreak':     '**ebreak** — Trigger breakpoint trap',
  'fence':      '**fence** `pred, succ` — Memory/IO ordering fence',

  // ── C Extension (compressed 16-bit) ──────────────────────────────────────────
  'c.addi':     (ops) => `**c.addi** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compressed: \`${ops[0]??'?'} = ${ops[0]??'?'} + sign_ext(${ops[1]??'?'})\` (imm ≠ 0)`,
  'c.addi16sp': (ops) => `**c.addi16sp** \`${ops[0]??'?'}\` — Compressed: \`sp = sp + sign_ext(${ops[0]??'?'}*16)\``,
  'c.addi4spn': (ops) => `**c.addi4spn** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compressed: \`${ops[0]??'?'} = sp + zero_ext(${ops[1]??'?'}*4)\``,
  'c.li':       (ops) => `**c.li** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compressed load immediate: \`${ops[0]??'?'} = ${ops[1]??'?'}\``,
  'c.lui':      (ops) => `**c.lui** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compressed load upper immediate`,
  'c.mv':       (ops) => `**c.mv** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compressed move: \`${ops[0]??'?'} = ${ops[1]??'?'}\``,
  'c.add':      (ops) => `**c.add** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compressed add: \`${ops[0]??'?'} = ${ops[0]??'?'} + ${ops[1]??'?'}\``,
  'c.sub':      (ops) => `**c.sub** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compressed subtract: \`${ops[0]??'?'} = ${ops[0]??'?'} - ${ops[1]??'?'}\``,
  'c.and':      (ops) => `**c.and** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compressed bitwise AND`,
  'c.or':       (ops) => `**c.or** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compressed bitwise OR`,
  'c.xor':      (ops) => `**c.xor** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compressed bitwise XOR`,
  'c.slli':     (ops) => `**c.slli** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compressed shift left logical`,
  'c.srli':     (ops) => `**c.srli** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compressed shift right logical`,
  'c.srai':     (ops) => `**c.srai** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compressed shift right arithmetic`,
  'c.andi':     (ops) => `**c.andi** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compressed AND with immediate`,
  'c.lw':       (ops) => `**c.lw** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compressed load word: \`${ops[0]??'?'} = mem[${ops[1]??'?'}]\``,
  'c.sw':       (ops) => `**c.sw** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compressed store word: \`mem[${ops[1]??'?'}] = ${ops[0]??'?'}\``,
  'c.lwsp':     (ops) => `**c.lwsp** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compressed load word from stack pointer`,
  'c.swsp':     (ops) => `**c.swsp** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compressed store word to stack pointer`,
  'c.j':        (ops) => `**c.j** \`${ops[0]??'?'}\` — Compressed unconditional jump`,
  'c.jr':       (ops) => `**c.jr** \`${ops[0]??'?'}\` — Compressed jump to register`,
  'c.jal':      (ops) => `**c.jal** \`${ops[0]??'?'}\` — Compressed jump and link (RV32 only)`,
  'c.jalr':     (ops) => `**c.jalr** \`${ops[0]??'?'}\` — Compressed jump and link register`,
  'c.beqz':     (ops) => `**c.beqz** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compressed branch if ${ops[0]??'?'} == 0`,
  'c.bnez':     (ops) => `**c.bnez** \`${ops[0]??'?'}, ${ops[1]??'?'}\` — Compressed branch if ${ops[0]??'?'} ≠ 0`,
  'c.ebreak':   '**c.ebreak** — Compressed breakpoint trap',
};
